USE QLDA
--B3_C1
SELECT *
FROM NHANVIEN
WHERE PHG=4
--B3_C2
SELECT *
FROM NHANVIEN
WHERE Luong>3000
--B3_C3
SELECT *
FROM NHANVIEN
WHERE (Luong>25000 AND PHG=4)
     OR (Luong>30000 AND PHG=5)
--B3_C4
SELECT HONV+ ' ' + TENLOT+ ''+TENNV AS 'HỌ VÀ TÊN'
FROM NHANVIEN
WHERE DCHI LIKE N'%TP HCM%'
--B3_C5
SELECT HONV+ ' ' + TENLOT+ ''+TENNV AS 'HỌ VÀ TÊN'
FROM NHANVIEN
WHERE HONV LIKE N'N%'
--B3_C6
SELECT NGSINH, DCHI
FROM NHANVIEN
WHERE HONV=N'Đinh'
	AND TENLOT=N'Bá'
	AND TENNV=N'Tiên'
select * from NHANVIEN
select * from THANNHAN
SELECT * FROM DEAN
select * from PHONGBAN
SELECT * FROM CONGVIEC
SELECT * FROM PHANCONG

--B4_C1 Hien thi danh sach than nhan cua nhan vien dinh ba tien
SELECT *
FROM THANNHAN, NHANVIEN
WHERE  THANNHAN.MA_NVIEN=NHANVIEN.MANV
	AND HONV=N'Đinh'
	AND TENLOT=N'Bá'
	AND TENNV=N'Tiên'
--B4_C2 Hien thi ten cac cong viec cua de an tin hoc hoa
SELECT TEN_CONG_VIEC
FROM DEAN,CONGVIEC
WHERE DEAN.MADA=CONGVIEC.MADA
	AND TENDEAN LIKE N'Tin học hóa'
--B4_C3 Hien thi ten phòng ban tham gia nhieu de an hơn 
--số de an cua phòng điều hành
SELECT DEAN.PHONG, PHONGBAN.TENPHG,COUNT(DEAN.MADA) AS 'Số Đề Án'
FROM DEAN,PHONGBAN
WHERE DEAN.PHONG=PHONGBAN.MAPHG
GROUP BY DEAN.PHONG,PHONGBAN.TENPHG
HAVING COUNT(DEAN.MADA) >
	(SELECT COUNT(DEAN.MADA) 
	FROM DEAN,PHONGBAN
	WHERE DEAN.PHONG=PHONGBAN.MAPHG
		AND PHONGBAN.TENPHG LIKE N'%Điều hành%'
	)



	



