ALTER TABLE PHONGBAN ADD TRPHG nvarchar(15) 
ALTER TABLE PHONGBAN ADD NG_NHANCHUC date
DROP TABLE NHANVIEN
DROP TABLE PHONGBAN
CREATE TABLE PHONGBAN (
	MaPHG int IDENTITY(1,1) PRIMARY KEY,
	TenPHG nvarchar(15) NOT NULL,
	TRPHG nvarchar(15),
	NG_NHANCHUC date
)
--DROP TABLE PHONGBAN
--ALTER TABLE NHANVIEN DROP CONSTRAINT FK_NV_PB
--ALTER TABLE PHONGBAN ALTER COLUMN TRPHG varchar(9)
--ALTER TABLE NHANVIEN ALTER COLUMN DCHI nvarchar(100)
CREATE TABLE NHANVIEN (
	MaNV varchar(9) PRIMARY KEY,
	HONV nvarchar(15) NOT NULL,
	TENLOT nvarchar(15) NOT NULL,
	TENNV nvarchar(15) NOT NULL,
	NGSINH date,
	DCHI nvarchar(30) NOT NULL,
	PHAI nvarchar(3) NOT NULL,
	LUONG float,
	MA_NQL varchar(9),
	PHG int
)
ALTER TABLE NHANVIEN ADD CONSTRAINT FK_NV_PB FOREIGN KEY(PHG) REFERENCES PHONGBAN(MaPHG)
ALTER TABLE NHANVIEN ADD CONSTRAINT FK_NV_NV FOREIGN KEY(MA_NQL) REFERENCES NHANVIEN(MaNV)
ALTER TABLE PHONGBAN ADD CONSTRAINT FK_PB_NV FOREIGN KEY(TRPHG) REFERENCES NHANVIEN(MaNV)

INSERT INTO PHONGBAN (TenPHG) VALUES (N'Quản Lý')
INSERT INTO PHONGBAN (TenPHG) VALUES (N'Nhân Sự')
INSERT INTO PHONGBAN (TenPHG) VALUES (N'Kinh Doanh')
INSERT INTO PHONGBAN (TenPHG) VALUES (N'Điều Hành')
INSERT INTO PHONGBAN (TenPHG) VALUES (N'Nghiên Cứu')

SELECT * FROM PHONGBAN
SELECT * FROM NHANVIEN

INSERT INTO NHANVIEN(MaNV,HONV,TENLOT,TENNV,NGSINH,DCHI,PHAI,LUONG,PHG)
 VALUES ('001',N'Lê',N'Quỳnh',N'Như','1967-02-01',N'291 Hồ Văn Huê,Tp Hồ Chí Minh',N'Nữ',43000,4)

 INSERT INTO NHANVIEN(MaNV,HONV,TENLOT,TENNV,NGSINH,DCHI,PHAI,LUONG,PHG)
 VALUES ('003',N'Trần',N'Thanh',N'Tâm','1957-05-04',N'34 Mai Thị Lự,Tp Hồ Chí Minh',N'Nam',25000,5),
 ('004',N'Nguyễn',N'Mạnh',N'Hùng','1967-03-04',N'95 Bà Rịa, Vũng Tàu',N'Nam',38000,5)

 INSERT INTO NHANVIEN(MaNV,HONV,TENLOT,TENNV,NGSINH,DCHI,PHAI,LUONG,PHG)
 VALUES ('005',N'Nguyễn',N'Thanh',N'Tùng','1962-08-20',N'22 Nguyễn Văn Cừ,Tp Hồ Chí Minh',N'Nam',40000,5)
 INSERT INTO NHANVIEN(MaNV,HONV,TENLOT,TENNV,NGSINH,DCHI,PHAI,LUONG,PHG)
 VALUES ('006',N'Phạm',N'Văn',N'Vinh','1965-01-01',N'45 Trưng Vương, Hà Nội',N'Nữ',55000,1)
 
 UPDATE NHANVIEN SET MA_NQL='006' WHERE MaNV='001'
 UPDATE PHONGBAN SET TRPHG='005' WHERE MaPHG=5
 UPDATE PHONGBAN SET NG_NHANCHUC='1978-05-22' WHERE MaPHG=5
 UPDATE NHANVIEN SET DCHI=N'95 Bà Rịa, Vũng Tàu' WHERE MaNV='004'
 UPDATE NHANVIEN SET DCHI=N'22 Nguyễn Văn Cừ, TP Hồ Chí Minh' WHERE MaNV='005'
 UPDATE NHANVIEN SET DCHI=N'45 Trưng Vương, Hà Nội' WHERE MaNV='006'